import path from "path";
import fs from "fs/promises";
import { cloneRepo, checkoutBranch, commitAll, pushBranch, isGitRepo } from "./git";
import { createPullRequest, type GitHubRepo } from "./github";
import { generateCopilotInstructions } from "./instructions";
import { ensureDir } from "../utils/fs";
import type { ProgressReporter } from "../utils/output";

export type ProcessResult = {
  repo: string;
  success: boolean;
  prUrl?: string;
  error?: string;
};

export type ProcessRepoOptions = {
  repo: GitHubRepo;
  token: string;
  branch?: string;
  model?: string;
  timeoutMs?: number;
  progress?: ProgressReporter;
};

export async function processRepo(options: ProcessRepoOptions): Promise<ProcessResult> {
  const { repo, token, branch = "primer/add-instructions", model = "gpt-4.1", timeoutMs = 120000, progress } = options;

  try {
    // Clone
    progress?.update(`${repo.fullName}: Cloning...`);
    const cacheRoot = path.join(process.cwd(), ".primer-cache");
    const repoPath = path.join(cacheRoot, repo.owner, repo.name);
    await ensureDir(repoPath);

    if (!(await isGitRepo(repoPath))) {
      const cleanUrl = repo.cloneUrl.replace(/\/+$/, "");
      const authedUrl = cleanUrl.replace("https://", `https://x-access-token:${token}@`);
      await cloneRepo(authedUrl, repoPath, { shallow: true, timeoutMs });
    }

    // Branch
    progress?.update(`${repo.fullName}: Creating branch...`);
    await checkoutBranch(repoPath, branch);

    // Generate instructions
    progress?.update(`${repo.fullName}: Generating instructions...`);
    let instructions: string;
    let timeoutId: ReturnType<typeof setTimeout>;
    const instructionsPromise = generateCopilotInstructions({
      repoPath,
      model,
      onProgress: (msg) => progress?.update(`${repo.fullName}: ${msg}`),
    });
    const timeoutPromise = new Promise<never>((_, reject) => {
      timeoutId = setTimeout(() => reject(new Error("Generation timed out")), timeoutMs);
    });
    try {
      instructions = await Promise.race([instructionsPromise, timeoutPromise]);
    } finally {
      clearTimeout(timeoutId!);
    }

    if (!instructions.trim()) {
      throw new Error("Generated instructions were empty");
    }

    // Write instructions
    const instructionsPath = path.join(repoPath, ".github", "copilot-instructions.md");
    await fs.mkdir(path.dirname(instructionsPath), { recursive: true });
    await fs.writeFile(instructionsPath, instructions, "utf8");

    // Commit
    progress?.update(`${repo.fullName}: Committing...`);
    await commitAll(repoPath, "chore: add copilot instructions via Primer");

    // Push
    progress?.update(`${repo.fullName}: Pushing...`);
    await pushBranch(repoPath, branch, token);

    // Create PR
    progress?.update(`${repo.fullName}: Creating PR...`);
    const prUrl = await createPullRequest({
      token,
      owner: repo.owner,
      repo: repo.name,
      title: "🤖 Add Copilot instructions via Primer",
      body: buildPrBody(),
      head: branch,
      base: repo.defaultBranch,
    });

    progress?.succeed(`${repo.fullName}: ${prUrl}`);
    return { repo: repo.fullName, success: true, prUrl };
  } catch (error) {
    const rawMsg = error instanceof Error ? error.message : "Unknown error";
    const errorMsg = rawMsg.replace(/x-access-token:[^@]+@/g, "x-access-token:***@");
    progress?.fail(`${repo.fullName}: ${errorMsg}`);
    return { repo: repo.fullName, success: false, error: errorMsg };
  }
}

export async function runBatchHeadless(
  repos: GitHubRepo[],
  token: string,
  progress?: ProgressReporter,
): Promise<ProcessResult[]> {
  const results: ProcessResult[] = [];
  for (let i = 0; i < repos.length; i++) {
    progress?.update(`[${i + 1}/${repos.length}] Processing ${repos[i].fullName}...`);
    const result = await processRepo({ repo: repos[i], token, progress });
    results.push(result);
  }
  progress?.done();
  return results;
}

function buildPrBody(): string {
  return [
    "## 🤖 Copilot Instructions Added",
    "",
    "This PR adds a `.github/copilot-instructions.md` file to help GitHub Copilot understand this codebase better.",
    "",
    "### What's Included",
    "",
    "The instructions file contains:",
    "- Project overview and architecture",
    "- Tech stack and conventions",
    "- Build/test commands",
    "- Key directories and files",
    "",
    "### Benefits",
    "",
    "With these instructions, Copilot will:",
    "- Generate more contextually-aware code suggestions",
    "- Follow project-specific patterns and conventions",
    "- Understand the codebase structure",
    "",
    "---",
    "*Generated by [Primer](https://github.com/pierceboggan/primer) - Prime your repos for AI*",
  ].join("\n");
}
